import type { ImportPayload } from "./types";

export const SAMPLE_OPENALTERNATIVE_DATA: ImportPayload = {
  source: "openalternative",
  alternatives: [
    {
      source_name: "Notion",
      source_slug: "notion",
      source_description: "Collaborative workspace and note-taking platform",
      source_url: "https://openalternative.co/alternatives/notion",
      category_hint: "ノート, Wiki",
      products: [
        {
          name: "AppFlowy",
          slug: "appflowy",
          short_description: "Open source workspace for notes, wikis, and project planning",
          website_url: "https://appflowy.io",
          github_url: "https://github.com/AppFlowy-IO/AppFlowy",
          license: "AGPL-3.0",
          github_stars: 69000,
          supports_japanese: false,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 1,
          reason_summary: "Notionに最も近いOSS代替。UIが直感的で機能も充実",
        },
        {
          name: "AFFiNE",
          slug: "affine",
          short_description: "Knowledge base and collaboration workspace",
          website_url: "https://affine.pro",
          github_url: "https://github.com/toeverything/AFFiNE",
          license: "MIT",
          github_stars: 67000,
          supports_japanese: false,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 2,
          reason_summary: "ホワイトボード機能を統合した次世代ワークスペース",
        },
        {
          name: "Outline",
          slug: "outline",
          short_description: "Beautiful wiki and knowledge base for teams",
          website_url: "https://www.getoutline.com",
          github_url: "https://github.com/outline/outline",
          license: "BSL-1.1",
          github_stars: 30000,
          supports_japanese: true,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 3,
          reason_summary: "チーム向けWikiに特化。日本語対応済み",
        },
      ],
    },
    {
      source_name: "Slack",
      source_slug: "slack",
      source_description: "Team communication platform",
      source_url: "https://openalternative.co/alternatives/slack",
      category_hint: "チャット, コラボレーション",
      products: [
        {
          name: "Mattermost",
          slug: "mattermost",
          short_description: "Secure collaboration platform for technical teams",
          website_url: "https://mattermost.com",
          github_url: "https://github.com/mattermost/mattermost",
          license: "AGPL-3.0",
          github_stars: 36000,
          supports_japanese: false,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 1,
          reason_summary: "エンタープライズ向けのセキュアなチャット",
        },
        {
          name: "Rocket.Chat",
          slug: "rocket-chat",
          short_description: "Flexible open source team chat",
          website_url: "https://rocket.chat",
          github_url: "https://github.com/RocketChat/Rocket.Chat",
          license: "MIT",
          github_stars: 45000,
          supports_japanese: false,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 2,
          reason_summary: "多機能で柔軟なチャットプラットフォーム",
        },
        {
          name: "Zulip",
          slug: "zulip",
          short_description: "Organized team chat with threading",
          website_url: "https://zulip.com",
          github_url: "https://github.com/zulip/zulip",
          license: "Apache-2.0",
          github_stars: 22000,
          supports_japanese: false,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 3,
          reason_summary: "スレッドベースの整理されたチャット",
        },
      ],
    },
    {
      source_name: "Typeform",
      source_slug: "typeform",
      source_description: "Online form builder and survey tool",
      source_url: "https://openalternative.co/alternatives/typeform",
      category_hint: "フォーム, アンケート",
      products: [
        {
          name: "Formbricks",
          slug: "formbricks",
          short_description: "Open source survey and forms platform",
          website_url: "https://formbricks.com",
          github_url: "https://github.com/formbricks/formbricks",
          license: "AGPL-3.0",
          github_stars: 9500,
          supports_japanese: false,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 1,
        },
        {
          name: "HeyForm",
          slug: "heyform",
          short_description: "Open source form builder",
          website_url: "https://heyform.net",
          github_url: "https://github.com/heyform/heyform",
          license: "AGPL-3.0",
          github_stars: 7500,
          supports_japanese: false,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 2,
        },
      ],
    },
    {
      source_name: "Shopify",
      source_slug: "shopify",
      source_description: "E-commerce platform for online stores",
      source_url: "https://openalternative.co/alternatives/shopify",
      category_hint: "EC, Eコマース",
      products: [
        {
          name: "Medusa",
          slug: "medusa",
          short_description: "Open source headless commerce engine",
          website_url: "https://medusajs.com",
          github_url: "https://github.com/medusajs/medusa",
          license: "MIT",
          github_stars: 28000,
          supports_japanese: false,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 1,
        },
        {
          name: "Saleor",
          slug: "saleor",
          short_description: "GraphQL-first headless e-commerce",
          website_url: "https://saleor.io",
          github_url: "https://github.com/saleor/saleor",
          license: "BSD-3-Clause",
          github_stars: 21000,
          supports_japanese: false,
          is_self_hostable: true,
          has_cloud: true,
          is_open_source: true,
          rank_order: 2,
        },
      ],
    },
  ],
};
