ALTER TABLE tools
ADD COLUMN IF NOT EXISTS forks_num INTEGER,
ADD COLUMN IF NOT EXISTS last_commit TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS language TEXT,
ADD COLUMN IF NOT EXISTS github_stars_updated_at TIMESTAMPTZ;